settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: pool.52kx.net # unique identifier
    name: pool.52kx.net
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://pool.52kx.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: 52kx.net
    name: 52kx.net
    description: 'Built for anything connected to the Internet.'
    url: 'https://52kx.net'
    method: GET
    expectStatus: 200

  - id: od.52kx.net
    name: od.52kx.net
    url: 'https://od.52kx.net/'
    method: GET
    expectStatus: 200
